version: '3.8'

services:
  # The Seq Logging Server (Local Developer Instance)
  cs24-seq:
    image: datalust/seq:latest
    container_name: cs24_seq_logs
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=True 
 # - SEQ_FIRSTRUN_ADMINPASSWORD=YourStrongPassword123!
    ports:
      - "5341:80" 
    volumes:
      - cs24_seq_data:/data
    restart: unless-stopped

# Ensures log data survives container restarts
volumes:
  cs24_seq_data: